name: Scott MacDonald, macdonaldster.ca
markdown: kramdown

#theme: jekyll-theme-midnight
#theme: minima
#gem "minima"


#remote_theme: poole/poole
future: true
title: macdonaldster.ca
description: A personal site, not a blog
exclude: [archive/]
logo: assets/sitelogo.jpg
google_analytics: UA-57864847-1
url: "http://macdonaldster.ca"

feed:
  collections:
    - pages

collections:
  category:
    output: true

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives

keep_files: [scripting]


excerpt_separator: <!--more-->

jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'