name: Scott MacDonald, macdonaldster.ca
markdown: kramdown

#theme: jekyll-theme-midnight
theme: minima

#remote_theme: poole/poole
future: true
title: macdonaldster.ca
description: A personal site, not a blog
exclude: [archive/]
include: ["pages"]
logo: assets/sitelogo.jpg
google_analytics: UA-57864847-1
url: "http://macdonaldster.ca"

feed:
  collections:
    - pages

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives

jekyll-archives:
  enabled: [categories]
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'