name: Scott MacDonald, macdonaldster.ca
markdown: kramdown
#theme: jekyll-theme-midnight
future: true
title: macdonaldster.ca
description: A personal site, not a blog
exclude: [archive/]
logo: assets/sitelogo.jpg
google_analytics: UA-57864847-1
plugins: [jekyll-include-cache]
remote_theme: "mmistakes/minimal-mistakes@4.16.5"