name: Scott MacDonald, macdonaldster.ca
markdown: kramdown

#theme: jekyll-theme-midnight
theme: minima

#remote_theme: poole/poole
future: true
title: macdonaldster.ca
description: A personal site, not a blog
exclude: [archive/]
include: ["pages"]
logo: assets/sitelogo.jpg
google_analytics: UA-57864847-1
url: "http://macdonaldster.ca"

feed:
  collections:
    - pages

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

plugins:
  - jekyll-sitemap
  - jekyll-feed
